= Capaciteitskaart

The capacity heatmaps information model was defined to cover a superset of data
exchanged by the NL system operators. A minimum set of data is defined that all
operators are expected to conform to, along with a number of optional
properties and data types.

.Data Product
[d2,svg,theme=4]
----
grid-rows: 4
grid-columns: 3

horizontal-gap: 160
vertical-gap: 80

vars: {
  d2-config: {
    pad: 20
  }
}

UpdateInfo.class: enterprise
1.class: empty
2.class: empty

HeatmapDataSet.class: dataset
EnergyArea.class: grid
PostcodeArea.class: enterprise

3.class: empty
Work.class: enterprise
4.class: empty

DateTimeInterval.class: grid
WorkTimeSchedule.class: enterprise
5.class: empty

HeatmapDataSet -> UpdateInfo: "updated"
HeatmapDataSet -> DateTimeInterval: "valid"
HeatmapDataSet -> EnergyArea: "energy_areas"
EnergyArea -> Work: "works"
Work -> WorkTimeSchedule: "time_schedules"
WorkTimeSchedule -> DateTimeInterval: "schedule_interval"
EnergyArea -> PostcodeArea: "postcode_areas"

classes: {
  empty: {
    label: ""
    style: {
      fill: transparent
      stroke: transparent
    }
  }
  grid: {
    style: {
      fill: "#eccfcb"
      shadow: true
    }
  }
  enterprise: {
    style: {
      fill: "#d1e7c2"
      shadow: true
    }
  }
  market: {
    style: {
      fill: "#fffbef"
      shadow: true
    }
  }
  dataset: {
    style: {
      shadow: true
    }
  }
}

legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  iec61968_color: "" {
    style: {
      fill: "#d1e7c2"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61968_text: "IEC61968 (Enterprise)" {
    shape: text
  }
  iec61970_color: "" {
    style: {
      fill: "#eccfcb"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61970_text: "IEC61970 (Grid)" {
    shape: text
  }
  iec62325_color: "" {
    style: {
      fill: "#fffbef"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec62325_text: "IEC62325 (Market)" {
    shape: text
  }
}

classes: {
  empty: {
    label: ""
    style: {
      fill: transparent
      stroke: transparent
    }
  }
  grid: {
    style: {
      fill: "#eccfcb"
      shadow: true
    }
  }
  enterprise: {
    style: {
      fill: "#d1e7c2"
      shadow: true
    }
  }
  market: {
    style: {
      fill: "#fffbef"
      shadow: true
    }
  }
}
----

The data is intended to be presented as a hierarchy with a
xref:schema:class/HeatmapDataSet.adoc[`HeatmapDataSet`] at its root, followed
by xref:schema:class/EnergyArea.adoc[`EnergyArea`] nested inside the
`HeatmapDataSet`.

This information model is based in part on the `LTDS Capacity Heatmap
Information Model`, which itself is published under the `Open Government
License`, under ©Crown copyright 2024.

== Additional schemas

* xref:schema:attachment$schemas/json_schema/dp_capaciteitskaart.json_schema.json[JSON schema]
* xref:schema:attachment$examples/dp_capaciteitskaart_dso.example.json[Example DSO instance data]
* xref:schema:attachment$examples/dp_capaciteitskaart_tso.example.json[Example TSO instance data]
